/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAfEth, IAfEthInterface } from "../IAfEth";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "applyStrategyReward",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "depositRewards",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IAfEth__factory {
  static readonly abi = _abi;
  static createInterface(): IAfEthInterface {
    return new utils.Interface(_abi) as IAfEthInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IAfEth {
    return new Contract(address, _abi, signerOrProvider) as IAfEth;
  }
}
