/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IVotiumStrategy,
  IVotiumStrategyInterface,
} from "../IVotiumStrategy";

const _abi = [
  {
    inputs: [],
    name: "cvxPerVotium",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "depositRewards",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "validate",
        type: "bool",
      },
    ],
    name: "ethPerCvx",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVotiumStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IVotiumStrategyInterface {
    return new utils.Interface(_abi) as IVotiumStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVotiumStrategy {
    return new Contract(address, _abi, signerOrProvider) as IVotiumStrategy;
  }
}
