/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IVotiumStrategyInterface extends utils.Interface {
  functions: {
    "cvxPerVotium()": FunctionFragment;
    "depositRewards(uint256)": FunctionFragment;
    "ethPerCvx(bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "cvxPerVotium",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositRewards",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "ethPerCvx", values: [boolean]): string;

  decodeFunctionResult(
    functionFragment: "cvxPerVotium",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ethPerCvx", data: BytesLike): Result;

  events: {};
}

export interface IVotiumStrategy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IVotiumStrategyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cvxPerVotium(overrides?: CallOverrides): Promise<[BigNumber]>;

    depositRewards(
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ethPerCvx(
      validate: boolean,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  cvxPerVotium(overrides?: CallOverrides): Promise<BigNumber>;

  depositRewards(
    amount: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ethPerCvx(validate: boolean, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    cvxPerVotium(overrides?: CallOverrides): Promise<BigNumber>;

    depositRewards(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    ethPerCvx(validate: boolean, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    cvxPerVotium(overrides?: CallOverrides): Promise<BigNumber>;

    depositRewards(
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ethPerCvx(validate: boolean, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    cvxPerVotium(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositRewards(
      amount: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ethPerCvx(
      validate: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
